# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 19:51
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='შეიქმნა')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='განახლდა')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='სახელი')),
                ('lastname', models.CharField(blank=True, max_length=40, null=True, verbose_name='გვარი')),
                ('sex', models.CharField(choices=[('0', 'ქალი'), ('1', 'კაცი')], max_length=1, verbose_name='გვარი')),
                ('born_date', models.DateTimeField(blank=True, null=True, verbose_name='დაბადების თარიღი')),
                ('death_date', models.DateTimeField(blank=True, null=True, verbose_name='გარდაცვალების თარიღი')),
                ('dossier', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='დოსიე')),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='prof_imgs/', verbose_name='სურათი')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='სურათი')),
                ('children', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='hierarchy.PersonModel', verbose_name='შვილები')),
                ('wife', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wife_set', to='hierarchy.PersonModel', verbose_name='მეუღლე')),
            ],
            options={
                'verbose_name': 'პიროვნება',
                'verbose_name_plural': 'პიროვნებები',
            },
        ),
    ]
